### ISSUE TITLE
Styles and clean code

### ISSUE THREAD

**Issue by neuville11** [pacocd/MH-first-week-profile#1]
- I noticed that your social media in the icons section is very close one to another, you could separate them
- the script tag not a good practice, add a js file, require it in your html file and write your code there, with this you can avoid to write the same js code in each section
- avoid white lines, try to order your code into blocks, your identation is really good

**Comment by ycosio** [comment]
Include a general js file to write any JavaScript function that you need like this:

<script type="text/javascript">
        $(".button-collapse").sideNav();
</script>

**Comment by pacocd** [comment]
Thanks! It's done!
