### ISSUE TITLE
Pixelated image

### ISSUE THREAD

**Issue by azaroma** [pacocd/MH-first-week-profile#5]
What's up, Paco! Your page took me by surprise because after reviewing our colleagues' pages I wasn't expecting one like yours: one that uses many pages. So that's a nice detail, along with the design of yours that I think is quite unique. The only thing I will complain about, is that your background image doesn't have  the necessary resolution and it looks pixelated. Aside from that I must tell you that the side menu is really great. Good evening, buddy!

**Comment by pacocd** [comment]
Hi Alejandro! I forgot to resize the background image, thanks for the comment! It's fixed :D
